# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# Configure Using Gemfile
# gem 'pg'
#
# development:
#   adapter: postgresql
#   database: development
#   pool: 5
#   timeout: 5000
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: wt_production
test:
  <<: *default
  database: wt_test
development:
  <<: *default
  database: wt_development